name: Evaluate FlowDroid Latest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job
#################################################################################################################################
#                                             Evaluate FlowDroid 2.7.1
#################################################################################################################################
  Evaluate-FlowDroid-2-7-1:
######################################################################
#                 Setup environments 
######################################################################
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      BREW: /home/runner/work/TaintBench/TaintBench/TBFramework/BREW-2.0.0-SNAPSHOT-EMSE 
      TBMAPPER: /home/runner/work/TaintBench/TaintBench/TBFramework/TBSaSMapper-1.0-SNAPSHOT-EMSE
      TOOL: /home/runner/work/TaintBench/TaintBench/AnalysisTools/FlowDroid-2.14.1
      VERSION: fd2141
      CONFIG: /home/runner/work/TaintBench/TaintBench/taintbench_brew_configs/fd2141
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install java 8
    - uses: actions/setup-java@v1
      with:
        distribution: temurin
        java-version: '17' # The JDK version to make available on the path.
    - run: java -version  
######################################################################
#                 Download TaintBench Framework Tools 
######################################################################
#########################################
#        BREW 
#########################################
    - name: Download BREW
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TBFramework'
        path: download
        file: BREW-2.0.0-SNAPSHOT-EMSE.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq download/BREW-2.0.0-SNAPSHOT-EMSE.zip -d TBFramework

    - run: ls TBFramework/BREW-2.0.0-SNAPSHOT-EMSE

#########################################
#      TBMapper
#########################################
    - name: Download TBMapper
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TBFramework'
        path: download
        file: TBSaSMapper-1.0-SNAPSHOT-EMSE.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq download/TBSaSMapper-1.0-SNAPSHOT-EMSE.zip -d TBFramework

    - run: ls TBFramework/TBSaSMapper-1.0-SNAPSHOT-EMSE

######################################################################
#                 Download Android Platforms  
######################################################################
    - name: Download Android Platforms
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'AndroidPlatforms'
        path: download
        file: platforms.zip 
    
    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq download/platforms.zip -d .

    - run: ls platforms

######################################################################
#                 Download TaintBench Suite
######################################################################
    - name: Download TaintBench Suite
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintBenchSuite'
        path: download
        file: TaintBench.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq download/TaintBench.zip -d TaintBench

    - run: ls TaintBench

    - name: Download TaintBench Baseline Findings
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: TaintBench/TaintBench
        tag: 'TaintBenchSuite'
        path: download
        file: findings.zip

    - name: Unzip
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq download/findings.zip -d .

######################################################################
#                 Download Analysis Tools 
######################################################################
###########################################
#                   FlowDroid April 2.7.1          
############################################
    - name: Checkout latest Flowdroid
      uses: actions/checkout@v4
      with:
        repository: secure-software-engineering/FlowDroid
        tag: 'TaintAnalysisTools'
        path: AnalysisTools/FlowDroid-2.14.1
        ref: v2.14.1

    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install -y maven

    - name: Build FlowDroid
      run: |
        cd AnalysisTools/FlowDroid-2.14.1
        mvn clean package -DskipTests

    - name: Verify FlowDroid Build
      run: ls AnalysisTools/FlowDroid-2.14.1/soot-infoflow/target
        
######################################################################
    - name: Remove .Zip files
      run: |
          sudo rm -rf download
    
    - run: ls platforms

    - run: ls TaintBench

    - run: ls findings
    
    - run: ls TBFramework/BREW-2.0.0-SNAPSHOT-EMSE

    - run: ls TBFramework/TBSaSMapper-1.0-SNAPSHOT-EMSE

    - run: ls AnalysisTools/FlowDroid-2.14.1


    - name: List taintbench_brew_configs
      run: ls -R /home/runner/work/TaintBench/TaintBench/taintbench_brew_configs/
######################################################################
#                 Run FlowDroid 2.7.1
######################################################################
######################################################################
    - name: Prepare
      run: |
          echo make sure the scripts are executable
          sudo cp taintbench_brew_configs/flushMemory.sh $BREW/flushMemory.sh
          sudo cp taintbench_brew_configs/killpid.sh $BREW/killpid.sh
          sudo chmod +x $BREW/flushMemory.sh
          sudo chmod +x $BREW/killpid.sh
         
          echo copy the script clear.sh to clear previous analysis results and make sure it is executable 
          sudo cp $CONFIG/clear.sh $TOOL/clear.sh
          sudo chmod +x $TOOL/clear.sh
          
          echo copy the configured config.properties to the BREW Folder 
          echo remove $BREW/config.properties
          sudo rm $BREW/config.properties
          echo copy taintbench_brew_configs/config.properties to $BREW/config.properties
          sudo mv taintbench_brew_configs/config.properties $BREW/config.properties
          
          echo copy the taintbench_brew_configs folder to the BREW folder 
          sudo mv taintbench_brew_configs $BREW/taintbench_brew_configs

    - name: Run FlowDroid 2.7.1
      run: |
          echo create $TOOL/savedResults folder to storing analysis results 
          sudo mkdir $TOOL/savedResults             
          
          echo create $TOOL/results folder to store intermediate result of each apk. 
          sudo mkdir $TOOL/results
          
          echo create $TBMAPPER/results folder to store list of sources and sinks for each apk 
          sudo mkdir $TBMAPPER/results
          
          echo make sure folder TBFramework and AnalysisTools have all permissions
          sudo chmod -R 777 TBFramework
          sudo chmod -R 777 AnalysisTools
          
          echo cd to directory of $BREW to execute it 
          cd $BREW
          java -jar BREW-2.0.0-SNAPSHOT.jar -data data/data_taintbench_16_06_20.zip -d detailed -c taintbench_brew_configs/$VERSION/config.xml -rules taintbench_brew_configs/$VERSION/TaintBench/rules_3.xml -r -nogui -t 20m 2>&1 | tee taintbench_log.txt 
          sudo mkdir upload
          sudo mv data/data_taintbench_16_06_20.zip upload/data_taintbench.zip
          sudo cp taintbench_log.txt upload/taintbench_log.txt
     
    - name: Print Evaluation Results
      run: tail -5 TBFramework/BREW-2.0.0-SNAPSHOT-EMSE/upload/taintbench_log.txt

    - name: Print Saved Results of FlowDroid 2.14.1
      run: |
           ls -R $BREW
           ls -R $TOOL

    - uses: actions/upload-artifact@v4
      with:
       name: BREW-Benchmark-Result-File-FlowDroid-2.14.1
       path: TBFramework/BREW-2.0.0-SNAPSHOT-EMSE/upload
    
    - uses: actions/upload-artifact@v4
      with:
       name: Raw-Results-of-FlowDroid-2.14.1
       path: AnalysisTools/FlowDroid-2.14.1/savedResults
       
    - uses: actions/upload-artifact@v4
      with:
       name: Source-And-Sinks-2.14.1
       path: TBFramework/TBSaSMapper-1.0-SNAPSHOT-EMSE/results
    
